CC	= g++

all:	stat bag

stat:	statistician2_main.cpp statistician2.cpp statistician2.h
	$(CC) -o statistician2 statistician2_main.cpp statistician2.cpp

bag: 	bag1_main.cpp bag1.cxx bag1.h
	$(CC) -o bag1 bag1_main.cpp bag1.cxx

clean:	rm -f statistician2 bag1
